---
- name: Install and start Apache Httpd
  hosts: clients
  tasks:
    - name: verify httpd package is present
      yum:
        name: httpd
        state: present

    - name: correct index.html is present
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true